name: Generate and upload custom image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  release:
    types: published
  workflow_dispatch:

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate custom images
    steps:
      - name: Install qemu-img
        run: sudo apt-get update && sudo apt-get install -y qemu-utils
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Download official image and create custom images
        run: python run_all.py
      - name: Upload autologin image
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-autologin-img
          path: rpiosimage/*-autologin.img
          if-no-files-found: error
      - name: Upload autologin + ssh image
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-autologin-ssh-img
          path: rpiosimage/*-autologin-ssh.img
          if-no-files-found: error
      - name: Upload autologin + ssh + expanded image
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-autologin-ssh-expanded-img
          path: rpiosimage/*-autologin-ssh-expanded.img
          if-no-files-found: error
      - name: Upload Mu image
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-mu
          path: rpiosimage/*-mu.img
          if-no-files-found: error

  release-asset:
    name: Upload artifact as GH Release asset
    needs: gen-image
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Get the GH Release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Download autologin OS image
        uses: actions/download-artifact@v2
        id: download-zip-autologin
        with:
          name: raspberry-pi-os-autologin-img
          path: autologin
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-autologin.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin.zip ./*
      - name: Upload autologin OS image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-autologin.outputs.download-path}}/raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin.zip
          asset_name: raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin.zip
          asset_content_type: application/zip

      - name: Download autologin + ssh OS image
        uses: actions/download-artifact@v2
        id: download-zip-autologin-ssh
        with:
          name: raspberry-pi-os-autologin-ssh-img
          path: autologin-ssh
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-autologin-ssh.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin-ssh.zip ./*
      - name: Upload autologin + ssh OS image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-autologin-ssh.outputs.download-path}}/raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin-ssh.zip
          asset_name: raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin-ssh.zip
          asset_content_type: application/zip

      - name: Download autologin + ssh + expanded OS image
        uses: actions/download-artifact@v2
        id: download-zip-autologin-ssh-expanded
        with:
          name: raspberry-pi-os-autologin-ssh-expanded-img
          path: autologin-ssh-expanded
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-autologin-ssh-expanded.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin-ssh-expanded.zip ./*
      - name: Upload autologin + ssh OS image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-autologin-ssh-expanded.outputs.download-path}}/raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin-ssh-expanded.zip
          asset_name: raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-autologin-ssh-expanded.zip
          asset_content_type: application/zip

      - name: Download Mu image
        uses: actions/download-artifact@v2
        id: download-zip-mu
        with:
          name: raspberry-pi-os-mu
          path: mu
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-mu.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-mu.zip ./*
      - name: Upload Mu image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-mu.outputs.download-path}}/raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-mu.zip
          asset_name: raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-mu.zip
          asset_content_type: application/zip
